

version: "3.7"
services:
  order-service:
    image: lolaakin/order-service:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    environment:
      # - ORDER_QUEUE_URI=amqps://pet-store.servicebus.windows.net
      # - ORDER_QUEUE_USERNAME=RootManageSharedAccessKey
      # - ORDER_QUEUE_PASSWORD=W0+3Slh1ZriCyWbUjt8vmp75arT1BK8Pk+ASbCmW2dk=
      # - ORDER_QUEUE_NAME=orders
      # - USE_WORKLOAD_IDENTITY_AUTH=false
      # - ORDER_DB_URI=mongodb://mongodb:27017
      # - ORDER_DB_NAME=orderdb
      # - ORDER_DB_COLLECTION_NAME=orders
      # - ORDER_DB_USER=
      # - ORDER_DB_PASSWORD=
      - ORDER_QUEUE_URI=amqps://my-eventbus-8915.servicebus.windows.net
      - ORDER_QUEUE_PORT=5671
      - ORDER_QUEUE_USERNAME=RootManageSharedAccessKey
      - ORDER_QUEUE_PASSWORD=HLF3Z+u8+fNAbr5THN0iRJ1PLby2GGObJ+ASbCfceXI=
      - ORDER_QUEUE_NAME=orders
      - ORDER_DB_URI=mongodb://mongodb:27017
      - ORDER_DB_NAME=orderdb
      - ORDER_DB_COLLECTION_NAME=orders
      - USE_WORKLOAD_IDENTITY_AUTH=false # Adjust if you're using Managed Identity instead
    networks:
      - backend_services
 
networks:
  backend_services:
    driver: bridge